# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/matthew/w/g/gameboy-emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/matthew/w/g/gameboy-emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthew/w/g/gameboy-emulator/CMakeFiles /home/matthew/w/g/gameboy-emulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/matthew/w/g/gameboy-emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GameboyEmulator

# Build rule for target.
GameboyEmulator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GameboyEmulator
.PHONY : GameboyEmulator

# fast build rule for target.
GameboyEmulator/fast:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/build
.PHONY : GameboyEmulator/fast

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/cpu.o: src/cpu.cpp.o

.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i

.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s

.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/helper.o: src/helper.cpp.o

.PHONY : src/helper.o

# target to build an object file
src/helper.cpp.o:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/helper.cpp.o
.PHONY : src/helper.cpp.o

src/helper.i: src/helper.cpp.i

.PHONY : src/helper.i

# target to preprocess a source file
src/helper.cpp.i:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/helper.cpp.i
.PHONY : src/helper.cpp.i

src/helper.s: src/helper.cpp.s

.PHONY : src/helper.s

# target to generate assembly for a file
src/helper.cpp.s:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/helper.cpp.s
.PHONY : src/helper.cpp.s

src/ram.o: src/ram.cpp.o

.PHONY : src/ram.o

# target to build an object file
src/ram.cpp.o:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/ram.cpp.o
.PHONY : src/ram.cpp.o

src/ram.i: src/ram.cpp.i

.PHONY : src/ram.i

# target to preprocess a source file
src/ram.cpp.i:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/ram.cpp.i
.PHONY : src/ram.cpp.i

src/ram.s: src/ram.cpp.s

.PHONY : src/ram.s

# target to generate assembly for a file
src/ram.cpp.s:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/ram.cpp.s
.PHONY : src/ram.cpp.s

src/ram_subset.o: src/ram_subset.cpp.o

.PHONY : src/ram_subset.o

# target to build an object file
src/ram_subset.cpp.o:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/ram_subset.cpp.o
.PHONY : src/ram_subset.cpp.o

src/ram_subset.i: src/ram_subset.cpp.i

.PHONY : src/ram_subset.i

# target to preprocess a source file
src/ram_subset.cpp.i:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/ram_subset.cpp.i
.PHONY : src/ram_subset.cpp.i

src/ram_subset.s: src/ram_subset.cpp.s

.PHONY : src/ram_subset.s

# target to generate assembly for a file
src/ram_subset.cpp.s:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/ram_subset.cpp.s
.PHONY : src/ram_subset.cpp.s

src/test_runner.o: src/test_runner.cpp.o

.PHONY : src/test_runner.o

# target to build an object file
src/test_runner.cpp.o:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/test_runner.cpp.o
.PHONY : src/test_runner.cpp.o

src/test_runner.i: src/test_runner.cpp.i

.PHONY : src/test_runner.i

# target to preprocess a source file
src/test_runner.cpp.i:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/test_runner.cpp.i
.PHONY : src/test_runner.cpp.i

src/test_runner.s: src/test_runner.cpp.s

.PHONY : src/test_runner.s

# target to generate assembly for a file
src/test_runner.cpp.s:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/test_runner.cpp.s
.PHONY : src/test_runner.cpp.s

src/vpu.o: src/vpu.cpp.o

.PHONY : src/vpu.o

# target to build an object file
src/vpu.cpp.o:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/vpu.cpp.o
.PHONY : src/vpu.cpp.o

src/vpu.i: src/vpu.cpp.i

.PHONY : src/vpu.i

# target to preprocess a source file
src/vpu.cpp.i:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/vpu.cpp.i
.PHONY : src/vpu.cpp.i

src/vpu.s: src/vpu.cpp.s

.PHONY : src/vpu.s

# target to generate assembly for a file
src/vpu.cpp.s:
	$(MAKE) -f CMakeFiles/GameboyEmulator.dir/build.make CMakeFiles/GameboyEmulator.dir/src/vpu.cpp.s
.PHONY : src/vpu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... GameboyEmulator"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/helper.o"
	@echo "... src/helper.i"
	@echo "... src/helper.s"
	@echo "... src/ram.o"
	@echo "... src/ram.i"
	@echo "... src/ram.s"
	@echo "... src/ram_subset.o"
	@echo "... src/ram_subset.i"
	@echo "... src/ram_subset.s"
	@echo "... src/test_runner.o"
	@echo "... src/test_runner.i"
	@echo "... src/test_runner.s"
	@echo "... src/vpu.o"
	@echo "... src/vpu.i"
	@echo "... src/vpu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

